rm CMakeCache.txt

cmake .. \
-DUSE_DOUBLE=ON \
-DDEBUG=ON \
-DCMAKE_BUILD_TYPE=debug \
-DKokkos_ENABLE_HWLOC=ON \
-DCMAKE_CXX_COMPILER=/usr/local/bin/g++-10 \
-DKokkos_ENABLE_OPENMP=ON \
-DKokkos_ENABLE_DEBUG=ON \
-DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON \
-DCMAKE_VERBOSE_MAKEFILE=ON
